apply plugin: 'com.android.library'

android {
    compileSdk = 36
    // When bumping, make sure to update https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/co.epitre.aelf_lectures.yml
    // Version/name mapping is available on https://github.com/android/ndk/releases. In this case, r28c.
    ndkVersion '28.2.13676358'

    defaultConfig {
        minSdkVersion 21
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        integration {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            jniDebuggable true
        }
    }

    //sourceSets.main.jni.srcDirs = [] //disable automatic ndk-build call
    externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
    }
    namespace 'org.sqlite.database'
    lint {
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation 'com.android.support:support-annotations:28.0.0'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test:rules:1.0.2'
    testImplementation 'junit:junit:4.12'
}

allprojects {
    repositories {
        // The order in which you list these repositories matter.
        google()
        mavenCentral()
    }
}